#ifndef _CONTROLLER_PARAMS_FILE_quad_H
#define _CONTROLLER_PARAMS_FILE_quad_H
//This file is autogenerated by `generateController.py`.


#define GAIN_LQR_DFX_RATES_X (0.0716f)  //quad
#define GAIN_LQR_DFX_RATES_Y (0.0f)  //quad
#define GAIN_LQR_DFX_NORMAL_X (0.0f)  //quad
#define GAIN_LQR_DFX_NORMAL_Y (0.1f)  //quad
#define GAIN_LQR_DFY_RATES_X (0.0f)  //quad
#define GAIN_LQR_DFY_RATES_Y (0.0716f)  //quad
#define GAIN_LQR_DFY_NORMAL_X (-0.1f)  //quad
#define GAIN_LQR_DFY_NORMAL_Y (0.0f)  //quad
#endif //#define  _CONTROLLER_PARAMS_FILE_quad_H
