#ifndef _CONTROLLER_PARAMS_FILE_tri_H
#define _CONTROLLER_PARAMS_FILE_tri_H
//This file is autogenerated by `generateController.py`.
#define GAIN_LQR_DFX_RATES_X (0.03346f)  //tri
#define GAIN_LQR_DFX_RATES_Y (0.0f)  //tri
#define GAIN_LQR_DFX_NORMAL_X (-0.16843f)  //tri
#define GAIN_LQR_DFX_NORMAL_Y (0.10785f)  //tri
#define GAIN_LQR_DFY_RATES_X (0.0f)  //tri
#define GAIN_LQR_DFY_RATES_Y (0.03346f)  //tri
#define GAIN_LQR_DFY_NORMAL_X (-0.10785f)  //tri
#define GAIN_LQR_DFY_NORMAL_Y (-0.16843f)  //tri
#endif //#define  _CONTROLLER_PARAMS_FILE_tri_H
